sudo: required

language: python

services:
  - docker

before_install:
 - docker pull tp33/django
 - docker pull mysql:5.7.14
 - mkdir db
 - ls
 - docker run --name mysql -d -e MYSQL\_ROOT\_PASSWORD='$3cureUS' -v db:/var/lib/mysql  mysql:5.7.14
 - sleep 10
 - docker run -it --name mysql-cmdline --link mysql:db mysql:5.7.14 mysql -uroot -p'$3cureUS' -h db -e "create user 'www'@'%' identified by '$3cureUS'; create database cs4501 character set utf8; grant all on cs4501.* to 'www'@'%';"
 - docker rm mysql-cmdline
 - docker-compose up

script:
 - docker exec -it cs4501_models_1 bash
 - python app/project2/manage.py test
 - exit
after_script:
 - docker-compose rm
 - y
 - docker rm mysql
