sudo: required

dist: trusty

language: python

services:
  - docker

before_install:
 - docker pull tp33/django
 - docker pull mysql:5.7.14
 - mkdir db
 - docker run --name mysql -d -e MYSQL\_ROOT\_PASSWORD='$3cureUS' -v `pwd`/db:/var/lib/mysql  mysql:5.7.14
 - sleep 10
 - docker run -it --name mysql-cmdline --link mysql:db mysql:5.7.14 mysql -uroot -p'$3cureUS' -h db -e "create user 'www'@'%' identified by '$3cureUS'; create database cs4501 character set utf8; grant all on cs4501.* to 'www'@'%';"
 - docker rm mysql-cmdline
 
before_script:
 - docker-compose up -d
script:
 - docker exec -it cs4501_models_1 python /app/project2/manage.py test
after_script:
 - docker-compose stop
 - docker stop mysql
 - docker rm `docker ps -a -q`
 - docker rmi `docker images -q`
 - rm -rf db