models:
    image: tp33/django
    external_links:
      -  mysql:db
    volumes:
      - "$PWD/app:/app"
    ports:
      - "8002:8000"

    command: bash -c "bash /app/project2/script.sh"


exp:
    image: tp33/django
    links:
      -  models:models-api
      -  kafka:kafka
      -  es:es      
    volumes:
      - "$PWD/app:/app"
    ports:
      - "8001:8000"

    command: bash -c "mod_wsgi-express start-server --port 8000 --working-directory /app/exp --reload-on-changes /app/exp/exp/wsgi.py"


web:
    image: tp33/django
    links:
      -  exp:exp-api
    volumes:
      - "$PWD/app:/app"
    ports:
      - "8000:8000"

    command: bash -c "mod_wsgi-express start-server --port 8000 --working-directory /app/web --reload-on-changes /app/web/web/wsgi.py"

kafka:
   image: spotify/kafka
   container_name: kafka
   environment:
      ADVERTISED_HOST: kafka
      ADVERTISED_PORT: 9092
   hostname: kafka

es:
   image: elasticsearch:2.0
   container_name: es
   ports:
      - "9200:9200"

batch:
   image: tp33/django
   container_name: batch
   volumes:
     - "$PWD/app:/app"
   links:
      - kafka:kafka
      - es:es
   command: bash -c "python /app/search/indexing.py"
