models:
    image: tp33/django
    external_links:
      -  mysql:db
    volumes:
      - "$PWD/app:/app"
    ports:
      - "8002:8000"

    command: bash -c "bash /app/project2/script.sh"


exp:
    image: tp33/django
    links:
      -  models:models-api
      -  kafka:kafka
      -  es:es      
    volumes:
      - "$PWD/app:/app"
    ports:
      - "8001:8000"

    command: bash -c "mod_wsgi-express start-server --port 8000 --working-directory /app/exp --reload-on-changes /app/exp/exp/wsgi.py"


web:
    image: tp33/django
    links:
      -  exp:exp-api
    volumes:
      - "$PWD/app:/app"
    ports:
      - "8000:8000"

    command: bash -c "mod_wsgi-express start-server --port 8000 --working-directory /app/web --reload-on-changes /app/web/web/wsgi.py"

kafka:
   image: spotify/kafka
   container_name: kafka
   environment:
      ADVERTISED_HOST: kafka
      ADVERTISED_PORT: 9092
   hostname: kafka

es:
   image: elasticsearch:2.0
   container_name: es
   ports:
      - "9200:9200"

batch:
   image: tp33/django
   container_name: batch
   volumes:
     - "$PWD/app:/app"
   links:
      - kafka:kafka
      - es:es
   command: bash -c "bash /app/search/batchScript.sh"

spark-master:
  image: gettyimages/spark
  command: bin/spark-class org.apache.spark.deploy.master.Master -h spark-master
  container_name: spark-master
  hostname: spark-master
  environment:
    MASTER: spark://spark-master:7077
    SPARK_CONF_DIR: /conf
  expose:
    - 7001
    - 7002
    - 7003
    - 7004
    - 7005
    - 7006
    - 7077
    - 6066
  ports:
    - 4040:4040
    - 6066:6066
    - 7077:7077
    - 8080:8080
  volumes:
    - ./data:/tmp/data

spark-worker:
  image: gettyimages/spark
  command: bin/spark-class org.apache.spark.deploy.worker.Worker spark://spark-master:7077
  container_name: spark-worker
  hostname: spark-worker
  environment:
    SPARK_CONF_DIR: /conf
    SPARK_WORKER_CORES: 2
    SPARK_WORKER_MEMORY: 512m
    SPARK_WORKER_PORT: 8881
    SPARK_WORKER_WEBUI_PORT: 8081
  links:
    - spark-master
  expose:
    - 7012
    - 7013
    - 7014
    - 7015
    - 7016
    - 8881
  ports:
    - 8081:8081
  volumes:
    - ./data:/tmp/data
